version: '3.3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 6000:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database